#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

This project is no longer maintained for VDI please use:
https://github.com/linuxserver/docker-webtop
For web based docker management try:
https://github.com/SelfhostedPro/Yacht
https://www.portainer.io/


******************************************************
******************************************************'
